/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.*;
/**
 *
 * @author archdri
 */
public class MonsterView extends javax.swing.JPanel {

    private Monster monsterModel;
    
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterBadConsequence = new GUI.BadConsequenceView();
        monsterName = new javax.swing.JLabel();
        combatLevel = new javax.swing.JLabel();
        levelVSCultist = new javax.swing.JLabel();
        prize = new javax.swing.JLabel();
        textbadConsequence = new javax.swing.JLabel();
        monsterPrize = new GUI.PrizeView();
        txtCombatLevel = new javax.swing.JPanel();
        badConsequenceView = new GUI.BadConsequenceView();

        monsterName.setText("Name");

        combatLevel.setText("CombatLevel");

        levelVSCultist.setText("LevelAgainstCultistPlayer");

        prize.setText("Prize");

        textbadConsequence.setText("BadConsequence");

        javax.swing.GroupLayout txtCombatLevelLayout = new javax.swing.GroupLayout(txtCombatLevel);
        txtCombatLevel.setLayout(txtCombatLevelLayout);
        txtCombatLevelLayout.setHorizontalGroup(
            txtCombatLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        txtCombatLevelLayout.setVerticalGroup(
            txtCombatLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textbadConsequence)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combatLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(monsterName)
                            .addComponent(levelVSCultist))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monsterPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prize)))
                    .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monsterName)
                    .addComponent(prize))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combatLevel)
                            .addComponent(txtCombatLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(levelVSCultist)
                        .addGap(18, 18, 18)
                        .addComponent(textbadConsequence))
                    .addComponent(monsterPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JLabel combatLevel;
    private javax.swing.JLabel levelVSCultist;
    private GUI.BadConsequenceView monsterBadConsequence;
    private javax.swing.JLabel monsterName;
    private GUI.PrizeView monsterPrize;
    private javax.swing.JLabel prize;
    private javax.swing.JLabel textbadConsequence;
    private javax.swing.JPanel txtCombatLevel;
    // End of variables declaration//GEN-END:variables

    public void setMonster(Monster aMonster){
        this.monsterModel = aMonster;
        this.monsterName.setText("Name:" + this.monsterModel.getName());
        this.combatLevel.setText("Level: " + Integer.toString(this.monsterModel.getCombatLevel()));
        this.levelVSCultist.setText("Level Against CultistPlayer:" + Integer.toString(this.monsterModel.getCombatLevelAgainstCultistPlayer()));
        repaint();
    }


}
